#!/bin/bash

echo “Starting...node with settings from json”

cd Documents/Projects/cdp/src/test/resources/

java -jar selenium-server-standalone-3.13.0.jar -role node -hub http://localhost:4444/grid/register -nodeConfig nodeconfig.json

echo "Done."